### PR TITLE
Fix build with QScintilla-2.10.3 (?)

### PR DESCRIPTION
**Pull request by a17r**
These changes were necessary to fix a build issue:
```
juffed-engine-qsci_autogen/HJY3QJUKGU/../../../juffed-0.10_p20160323/src/app/qsci/lexers/qscilexerada.h:7:19: error: expected identifier before numeric constant
 #define SCLEX_ADA 20
                   ^
```
See also: https://bugs.gentoo.org/652928

### CODE REVIEW

**Comment by agaida** [comment]
@Mezomish - please review and merge - i don't want to patch my debian packages with some not reviewed patches that are not even in upstream

**Comment by a17r** [comment]
ping

**Comment by tsjk** [comment]
Seems to work on my Gentoo system.
